const wordText = document.querySelector(".word"),
hintText = document.querySelector(".hint span"),
refreshBtn = document.querySelector(".refresh-word"),
checkBtn = document.querySelector(".check-word"),
inputField = document.querySelector("input");
let correctWord;
const initGame = () =>{
    //Generate a random number between 0 and the words.length
    //Words is an object containing the key-value pairs of 'word' and 'hint'
    let randomObj = words[Math.floor(Math.random() * words.length)];
    //Access the word generated by the randomObj function and split it using the split function
    let wordArray = randomObj.word.split("");
    //Initialise the for loop according to the words length and subtract by -1 because the array starts at 0 
    //The length function start at 1, so -1 inorder to take into account all alpahbets in the word
    //Keep running until the for loop is greater than 0
    //i = 7; i > 0 ; i --
    for(let i = wordArray.length -1 ;i > 0;i --){
        let j = Math.floor(Math.random() * i + 1);
        [wordArray[i], wordArray[j]] = [wordArray[j],wordArray[i]];
    }
    wordText.innerText = wordArray.join("");
    hintText.innerText = randomObj.hint;
    correctWord = randomObj.word.toLocaleLowerCase();
}
initGame();

const checkWord = ()=>{
    let userWord = inputField.value.toLocaleLowerCase();
    if(!userWord) return alert("Please input a word");
    if (userWord !== correctWord) return alert(`Sorry!${userWord} is wrong input`)
    else (alert(`Yes!${userWord} is correct`));
}

refreshBtn.addEventListener ("click", initGame);
checkBtn.addEventListener ("click", checkWord);